spring:
  application:
    name: server-rest
server:
  port: ${PORT:8090}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:8761}/eureka/

kafka:
  bootstrapAddress=http://localhost:9092: