services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  kafka:
    image: apache/kafka-native
    ports:
      - "9092:9092"
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  discover-server:
    image: discovery-server
    restart: always
    ports:
      - 8761:8761
    depends_on:
      - postgres
      - kafka

  server-grpc:
    image: server-grpc
    environment:
      EUREKA_HOST: discover-server
      POSTGRES_HOST: postgres
      KAFKA_HOST: kafka
      KAFKA_PORT: 9093
    restart: always
    depends_on:
      - discover-server

  server-rest:
    image: server-rest
    environment:
      EUREKA_HOST: discover-server
      POSTGRES_HOST: postgres
      KAFKA_HOST: kafka
      KAFKA_PORT: 9093
    restart: always
    depends_on:
      - discover-server
      - kafka

  server-ws:
    image: server-ws
    environment:
      EUREKA_HOST: discover-server
      POSTGRES_HOST: postgres
      KAFKA_HOST: kafka
      KAFKA_PORT: 9093
    restart: always
    depends_on:
      - discover-server

  server-stomp:
    image: server-stomp
    restart: always
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9093
    ports:
      - 8099:8099
    depends_on:
      - server-grpc
      - server-rest
      - server-ws

  client-feign:
    image: client-feign
    environment:
      EUREKA_HOST: discover-server
    depends_on:
      - server-rest

  client-rest:
    image: client-rest
    environment:
      EUREKA_HOST: discover-server
    depends_on:
      - server-rest

  client-grpc:
    image: client-grpc
    environment:
      EUREKA_HOST: discover-server
    depends_on:
      - server-grpc

  client-ws:
    image: client-ws
    environment:
      EUREKA_HOST: discover-server
    depends_on:
      - server-ws

volumes:
  postgres:
  pgadmin: