spring:
  application:
    name: server-grpc

datasource:
  url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/postgres
  username: postgres
  password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
grpc:
  server:
    port: ${GRPC_PORT:9090}

kafka:
  producer:
    enabled: true
  bootstrapAddress: http://${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}