spring:
  application:
    name: client-grpc

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

grpc:
  client:
    client:
      address: SERVER-GRPC
      negotiation-type: plaintext